# Generated by Django 3.2 on 2021-04-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_payment_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/projects'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='language',
            field=models.CharField(blank=True, choices=[('C#', 'C#'), ('C', 'C'), ('C++', 'C++'), ('CSS', 'CSS'), ('Erlang', 'Erlang'), ('Go', 'Go'), ('Haskell', 'Haskell'), ('HTML', 'HTML'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('NodeJS', 'NodeJS'), ('Perl', 'Perl'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Scala', 'Scala'), ('Shell', 'Shell'), ('VB', 'VB')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in review', 'in review'), ('taken', 'taken'), ('paid', 'paid'), ('closed', 'closed')], default='open', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('json', 'json'), ('xml', 'xml'), ('http', 'http')], max_length=255),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('merged', 'merged'), ('paid', 'paid')], default='open', max_length=250),
        ),
        migrations.AlterField(
            model_name='solution',
            name='url',
            field=models.URLField(help_text='Pull Request URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('paypal', 'Paypal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_service_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
    ]
